### ISSUE TITLE
Recent changes of the Gootloader zombied script, causes GootLoaderAutoJsDecode.py to fail

### ISSUE THREAD

**Issue by GootloaderSites** [mandiant/gootloader#1]
These samples are failing the autoJsDecode:
https://www.virustotal.com/gui/file/975fe5897c8b00c5a18c5bae04b40e3feb94f9a2deb201697dc7059bba2ad581
https://www.virustotal.com/gui/file/6e4d270446a5a47be01f8181890052819b67430e163116e5f78c66ce61a227f1

JS code they are hiding in, is based off this: https://unpkg.com/browse/material-design-lite@1.3.0/material.js
With certain lines removed.

**Comment by andy2002a** [comment]
@GootloaderSites they should work with the latest release.

**Comment by GootloaderSites** [comment]
Confirmed fixed. thank you!
